#!/bin/bash

# Stop previous instance of the bot if it's running
pkill Bot;

# Build the bot
cd ~/bots/AnilistConEnie;
dotnet build -c Release --source=https://api.nuget.org/v3/index.json;

# Start the bot
cd ~/bots/AnilistConEnie/bin/Release/net6.0/;
./Bot;
