<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <StartupObject>AnilistESP.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Datatypes\**" />
    <EmbeddedResource Remove="Datatypes\**" />
    <None Remove="Datatypes\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="firebase-anilistconenie.json" />
    <None Remove="firebase-yumiko.json" />
    <None Remove="firebase.json" />
    <None Remove="firebase_ejemplo.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="firebase-anilistconenie.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="firebase-yumiko.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="firebase_ejemplo.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="5.0.0-nightly-01633" />
    <PackageReference Include="DSharpPlus.CommandsNext" Version="5.0.0-nightly-01633" />
    <PackageReference Include="DSharpPlus.Interactivity" Version="5.0.0-nightly-01633" />
    <PackageReference Include="DSharpPlus.SlashCommands" Version="5.0.0-nightly-01633" />
    <PackageReference Include="Google.Cloud.Firestore" Version="3.0.0" />
    <PackageReference Include="GraphQL" Version="5.3.3" />
    <PackageReference Include="GraphQL-Parser" Version="8.0.0" />
    <PackageReference Include="GraphQL.Client" Version="5.0.2" />
    <PackageReference Include="GraphQL.Client.Abstractions" Version="5.0.2" />
    <PackageReference Include="GraphQL.Client.Abstractions.Websocket" Version="5.0.2" />
    <PackageReference Include="GraphQL.Client.Serializer.Newtonsoft" Version="5.0.2" />
    <PackageReference Include="GraphQL.Primitives" Version="5.0.2" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.43" />
    <PackageReference Include="ncrontab" Version="3.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="108.0.2-alpha.0.5" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0-preview.6.22324.4" />
    <PackageReference Include="Tomat.TatsuSharp" Version="1.0.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\frame-love.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
